---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[simple_passenger::default]
    attributes:
