language: ruby
rvm:
  - 2.2.5
sudo: true

before_script:
- source <(curl -sL https://raw.githubusercontent.com/atheiman/simple-passenger-cookbook/master/start_docker.sh)

script:
- bundle exec rspec
- travis_retry bundle exec rake integration:docker
