language: ruby

sudo: required

dist: trusty

rvm:
- 2.3.1

env:
- KITCHEN_REGEXP=centos-6.7
- KITCHEN_REGEXP=centos-7.2
- KITCHEN_REGEXP=ubuntu-14.04
- KITCHEN_REGEXP=ubuntu-16.04

services:
- docker

script:
- bundle exec rspec
- bundle exec rake integration:docker[test,$KITCHEN_REGEXP]
