language: ruby

cache: bundler

sudo: required

dist: trusty

before_install:
  # update core ruby dependencies
  - gem update --system
  - gem update bundler

rvm:
- 2.3.3

env:
- SUITE=chefspec
- SUITE=lint
- SUITE=centos-6
- SUITE=centos-7
- SUITE=ubuntu-14
- SUITE=ubuntu-16

services:
- docker

script:
- bundle exec ./.travis.sh

matrix:
  allow_failures:
  - env: SUITE=lint
  fast_finish: true
