language: ruby

cache: bundler

sudo: required

dist: trusty

before_install:
  - gem update --system
  - gem update bundler

rvm:
- 2.3.3

env:
- SUITE=chefspec
- SUITE=lint
- SUITE=centos
- SUITE=ubuntu

services:
- docker

script:
- bundle exec ./.travis.sh

matrix:
  allow_failures:
  - env: SUITE=lint
  fast_finish: true
